#! /bin/bash
cat <<EOF
ANDROID_NDK_ROOT: $ANDROID_NDK_ROOT
ANDROID_ARCH: $_ANDROID_ARCH
ANDROID_EABI: $_ANDROID_EABI
ANDROID_API: $ANDROID_API
ANDROID_SYSROOT: $ANDROID_SYSROOT
ANDROID_TOOLCHAIN: $ANDROID_TOOLCHAIN
CROSS_COMPILE: $CROSS_COMPILE
ANDROID_DEV: $ANDROID_DEV
EOF

