/*
 * Copyright (C) 2015 shimoda
 *
 * !!do not edit!!
 * this file is automatically generated by gradle and python script.
 */
package com.googlecode.pythonforandroid;

public class PythonUrls {
    public static final String URL_BIN =
        "https://github.com/kuri65536/python-for-android/releases/download/";
    public static final String URL_SRC =
        "https://raw.githubusercontent.com/kuri65536/python-for-android/master/";
}
