2to3 bluetooth_chat.py | patch
2to3 hello_world.py | patch
2to3 notify_weather.py | patch
2to3 say_chat.py | patch
2to3 say_time.py | patch
2to3 say_weather.py | patch
2to3 speak.py | patch
2to3 take_picture.py | patch
2to3 test.py | patch
2to3 weather.py | patch
